### ISSUE TITLE
Option to hide aim line - advanced play

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#24]
Straight forward like that. Have an option to remove the line before a game starts for us try hards :)

**Comment by Terri00** [comment]
I've ran out of data I can sync currently, but if there is a space to add it the future i will consider this

**Comment by MrDummyNL** [comment]
For visuals, the hit spot on white ball must ofc stay. VR is not always clear for hit spot ball.
But for advanced mode, the aim line can removed to make it more harder. :)

Only Desktop has slight advantage because cue is already perfect lined.... showed where ball will go.

**Comment by Reploidsham** [comment]
You can turn it off locally by using a simple_toggle button (in my case I cloned the reset button, removed the extra material and swapped the script for a simple toggle that pointed to the guide display)
You can't directly toggle gameobjects referenced by the udon script in the table itself or it breaks, but because the guideline is nested, you can safely disable or enable that one.
