### ISSUE TITLE
Better spin physics

### ISSUE THREAD

**Issue by Terri00** [Terri00/vrc8ball#36]
Want to add side spin / english spin to cue ball

Don't understand the maths correctly for this yet.

**Comment by dragonash2019** [comment]
I don't know if I can do much to help, but if you have a test build, I'm willing to use it.
It's difficult to explain the spin itself, but you need to be able to hit the side of the cue ball head on and still have the ball go straight, while spinning. Right now, regardless of how you have the pool stick angled, the ball will get pushed in the opposite trajectory (hit on the right side and it will move left)

Obviously you know this and your issue is the math. However, you do have top spin and bottom spin working. Thinking from a laymen standpoint, maybe if you are able to give us another "aim" point, it would work,

For ex:
We have the first "lock on" position, like we have now, but this position should just be focused on the part of the ball we want to hit.
A second "lock on" could be the white direction arrow.

The combination sounds like it could let us hit the ball on the side to get the spin, while aiming it correctly to hit the other ball in front of it.

I hope I don't sound obnoxious with suggesting this. I know nothing about programming, but just trying to look at alternative solutions.

**Comment by Terri00** [comment]
^^
I've sat down and picked up some physics papers to read. It gets quite involved but starting to understand it, should end up with a much more accurate simulation at the end of it.

The current code has no understanding of what 'rolling' is and is more of a hacked on solution, so this is where i've started

**Comment by dragonash2019** [comment]
omg those equations!! no mas! lol
I'll be honest, it's probably only for a niche community in an already niche VR community, but this could be a good multiplayer VR Pool simulator on it's own
