### ISSUE TITLE
The 0 Y prefab position is not "great" place for world 0 Y level.

### ISSUE THREAD

**Issue by MrDummyNL** [Terri00/vrc8ball#42]
You must aware many worlds are started around 0,0,0 level (let's say the floor is always 0 Y). Multi level worlds exists too.
In your instructions the prefab must placed at 0 Y. 
This is because the detection for desktop players, to put correctly stick at white ball.

But....

The 0,0,0 point in prefab is not at below level of the pool table (which is normal for ALL furniture prefabs!) but at playing area above the pool table. That means the world MUST lowered (-0,86 Y) or the pool table will sink inside floor.

Why can you not make 0,0,0 origin just under the legs of the pool table? Is detection not possible set at 0,86 Y height? Then the prefab can placed in every room without need to move everything down or up.

There are worlds where buildings are at like 5 metres above origin point, or even below (like go below to the cellar area) but the world creator must move whole world up or down for the pool game!

Yep, it less nice side of the pool prefab with strange 0 Y position above the pool table. Is it not possible to change detection place (or manually set the detection height so it will work on any level), like at 0,86 Y?

**Comment by Reploidsham** [comment]
Since that's largely dependent on a shader used by the pool table, I've already suggested to a couple people who know shader-fu to look at it. As of right now rotating the pool table also causes the aim line to be misaligned. If the shader is corrected, there would no longer be a position requirement on the table.

**Comment by MrDummyNL** [comment]
Yeah, hope it will better in future if this can detected and adjusted with Udon script?

**Comment by Terri00** [comment]
Yep the issue lies in the shaders like Reploidsham said.

The solution would be to supply another transform matrix to the shadow/line shader telling it the world transform of the pool table.
Note: There are 16 different materials for the shadows which all need to have that matrix set on them from code.

I left it like this simply because its simpler to manage.

Personally I think moving the entire world to accomodate this shader quirk is a fine requirement, so I won't be updating it myself.

**Comment by dragonash2019** [comment]
> Yep the issue lies in the shaders like Reploidsham said.
> 
> The solution would be to supply another transform matrix to the shadow/line shader telling it the world transform of the pool table.
> Note: There are 16 different materials for the shadows which all need to have that matrix set on them from code.
> 
> I left it like this simply because its simpler to manage.
> 
> Personally I think moving the entire world to accomodate this shader quirk is a fine requirement, so I won't be updating it myself.

I quite literally rotated my entire world to make it fit in the room properly yesterday lol
I'm fine with it

**Comment by MrDummyNL** [comment]
Also world creators, make sure world is already correct placed, especially if you make new world.
Because the spawn point will also move.

Means if world gets populair and you add later pool, forced to move world lower and/or rotate, the spawn point moves too. 
If you update at some time, late-joiners after update will "miss" others because they are in different world version. Imagine that weirdness.

So if you want add pool, rotate and position world now.
