### ISSUE TITLE
Normal colored balls in multiplayer

### ISSUE THREAD

**Issue by Ikrandas** [Terri00/vrc8ball#44]
You have them in the single player but not multiplayer and it feels more like real pool that way. Thanks so much in advance!

**Comment by Terri00** [comment]
Ya, need to improve the UI of whos turn it is since it currently can only use the edge light to show that. This of course makes things difficult when everything is different colours in the USA standard set ^^

It's a low priority for me right now, but for sure want to bring this to the game at some point

**Comment by Ikrandas** [comment]
No rush at all! Perhaps you could do like a dashed line around the edge for stripes and a normal one for solids
